# Generated by Django 3.2 on 2023-10-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=25)),
                ('std_gender', models.CharField(max_length=25)),
                ('std_age', models.IntegerField()),
                ('std_email', models.EmailField(max_length=254)),
                ('std_address', models.CharField(max_length=50)),
                ('std_phone', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
