# Generated by Django 3.2 on 2023-10-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_name',
            field=models.CharField(max_length=255),
        ),
    ]
